#!/usr/bin/env python3
"""
Onyx Systems — templatize data/newsletter.html from the canonical Daily Brief .md.

The Daily Brief content source of truth is the pointer file:
  /home/ai/Documents/Obsidian Vault/Daily/last_sent_newsletter.json  -> md_path
(only set after the email is confirmed sent; guarantees the website shows exactly
what was emailed). Falls back to the newest Newsletter - <DATE>.md on the date.

This script parses the brief markdown into:
  - alert headline + body (section after 🔴 ALERT)
  - "today in tech" bullets
  - daily tip (section after 💡 DAILY TIP)
  - the Far Side comic (assets/img/news/<DATE>-farside.jpg)
and writes a clean, themed newsletter.html in the site repo.

Run:  python3 scripts/build_newsletter_html.py [DATE]
"""
import os, re, json, datetime, sys, shutil

VAULT = "/home/ai/Documents/Obsidian Vault/Daily"
REPO = "/home/ai/onyx-systems-website"
DATA = os.path.join(REPO, "data")


def today_iso():
    return datetime.date.today().isoformat()


def resolve_md(date_str):
    ptr = os.path.join(VAULT, "last_sent_newsletter.json")
    if os.path.exists(ptr):
        try:
            p = json.load(open(ptr))
            mp = p.get("md_path")
            if mp and os.path.exists(mp) and date_str in mp:
                return mp, date_str
        except Exception:
            pass
    # fallback: prefer the timestamped brief (Newsletter - YYYY-MM-DD-HHMM.md) over plain date
    cands = [f for f in os.listdir(VAULT)
             if f.startswith("Newsletter - ") and f.endswith(".md") and date_str in f]
    # Prefer files with HHMM timestamp (generated by 08:00 cron)
    timestamped = [f for f in cands if re.search(r'Newsletter - \d{4}-\d{2}-\d{2}-\d{4}\.md$', f)]
    if timestamped:
        return os.path.join(VAULT, sorted(timestamped)[-1]), date_str
    # Fallback to plain date files
    plain = [f for f in cands if not re.search(r'Newsletter - \d{4}-\d{2}-\d{2}-\d{4}\.md$', f)]
    if plain:
        return os.path.join(VAULT, sorted(plain)[-1]), date_str
    return None, date_str


def extract_comic_caption(md, date_str=None):
    """Extract the Far Side comic caption from markdown.
    Looks for the ![Far Side comic: "caption"](farside_...) pattern.
    Validates the caption using the specialized farside_caption.py tool which
    properly extracts just the caption band from Far Side archive images.
    """
    m = re.search(r'!\[Far Side comic:\s*"([^"]+)"\]\(farside[^)]*\)', md)
    if m:
        caption = m.group(1).strip()
        # VERIFY: Check caption matches the actual comic image using farside_caption.py
        if date_str:
            comic_img = os.path.join("/home/ai/Documents/Obsidian Vault/Daily", f"farside_{date_str}.jpg")
            if os.path.exists(comic_img):
                try:
                    import subprocess
                    # Use the specialized farside_caption.py which properly extracts
                    # just the caption area (not the full comic panel)
                    result = subprocess.run(
                        ["python3", "/home/ai/farside_caption.py", comic_img],
                        capture_output=True, text=True, timeout=30
                    )
                    ocr_text = result.stdout.strip()
                    # Only trust OCR if it looks like clean human-readable English
                    # (reasonable word count, contains common English words, not garbled)
                    if (ocr_text and ocr_text != "NO_USABLE_CAPTION" 
                        and len(ocr_text) > 10 
                        and len(ocr_text) < 300
                        and _looks_like_valid_caption(ocr_text)):
                        caption_words = set(re.findall(r"[a-z']+", caption.lower()))
                        ocr_words = set(re.findall(r"[a-z']+", ocr_text.lower()))
                        # If caption shares significant words with OCR, keep markdown caption
                        # (they agree). If they share NO words but OCR looks valid,
                        # the markdown caption might be wrong - use OCR.
                        if caption_words & ocr_words:
                            pass  # They agree, keep markdown caption
                        elif not caption_words & ocr_words and len(ocr_words) > 5:
                            # OCR text IS the caption from the actual image, and looks valid
                            ocr_caption = ocr_text.strip().strip('"\'')
                            if len(ocr_caption) > 10:
                                caption = ocr_caption
                    # If OCR is garbage, keep the markdown caption (don't corrupt it)
                except (Exception, subprocess.TimeoutExpired):
                    pass  # If verification fails, keep original caption
        return caption
    # Fallback: any Far Side reference
    m = re.search(r'Far Side.*?"([^"]+)"', md)
    if m:
        return m.group(1).strip()
    return "The Far Side &mdash; your daily laugh."


def _looks_like_valid_caption(text: str) -> bool:
    """Heuristic: does this OCR text look like a valid Far Side caption vs garbage?"""
    if not text or len(text) < 8:
        return False
    
    # Count recognizable English words
    words = re.findall(r"[a-zA-Z]{2,}", text.lower())
    if len(words) < 3:
        return False
    
    # Common English words that should appear in a real caption
    common_words = {
        'the', 'and', 'or', 'but', 'if', 'then', 'when', 'where', 'why', 'how',
        'to', 'of', 'in', 'on', 'for', 'with', 'at', 'by', 'from', 'up', 'down',
        'out', 'off', 'over', 'under', 'again', 'once', 'just', 'not', 'no', 'yes',
        'well', 'oh', 'hey', 'wait', 'stop', 'help', 'please', 'thank', 'thanks',
        'sorry', 'excuse', 'pardon', 'so', 'what', 'who', 'this', 'that', 'there',
        'here', 'my', 'your', 'his', 'her', 'our', 'their', 'i', 'we', 'you', 'he',
        'she', 'it', 'they', 'me', 'us', 'him', 'them', 'a', 'an', 'is', 'are',
        'was', 'were', 'am', 'do', 'does', 'did', 'can', 'could', 'would', 'should',
        'will', 'have', 'has', 'had', 'say', 'said', 'tell', 'told', 'think', 'thought',
        'know', 'knew', 'see', 'saw', 'look', 'looked', 'get', 'got', 'give', 'gave',
        'take', 'took', 'make', 'made', 'go', 'went', 'come', 'came', 'want', 'wanted',
        'need', 'needed', 'like', 'liked', 'love', 'loved', 'hate', 'hated'
    }
    
    word_matches = sum(1 for w in words if w in common_words)
    # At least 30% of words should be common English words
    if word_matches / max(len(words), 1) < 0.3:
        return False
    
    # Reject if too many non-alphanumeric chars (garbage)
    alnum_ratio = sum(c.isalnum() or c.isspace() for c in text) / len(text)
    if alnum_ratio < 0.7:
        return False
    
    # Reject if it's mostly repeated characters (OCR noise)
    if len(set(text.lower())) < 15:
        return False
    
    return True


def extract_header_logo(md):
    """Extract the header logo image reference from markdown.
    Looks for ![Header Logo](onyxsystems-header.png) at the top."""
    m = re.search(r'!\[Header Logo\]\(([^)]+)\)', md)
    if m:
        return m.group(1).strip()
    return "onyxsystems-header.png"


def extract_tagline(md):
    """Extract the tagline 'Serving Lake City & North Florida' from markdown."""
    m = re.search(r'\*\*(Serving Lake City[^*]+)\*\*', md)
    if m:
        return m.group(1).strip()
    return "Serving Lake City & North Florida"


def extract_business_card(md):
    """Extract the business card image reference from markdown.
    Looks for ![Business Card](Onyx_Card.png) at the bottom."""
    m = re.search(r'!\[Business Card\]\(([^)]+)\)', md)
    if m:
        return m.group(1).strip()
    return "Onyx_Card.png"


def clean_tip_body(tip_body):
    """Remove mobile/phone references from tip body per brand rules."""
    # Remove lines containing phone/mobile/iphone/android references
    lines = tip_body.split('\n')
    cleaned = []
    for ln in lines:
        if re.search(r'(?i)\b(phone|mobile|iphone|android|tap the share)\b', ln):
            continue
        cleaned.append(ln)
    return '\n'.join(cleaned).strip()


def extract_comedy_break_title(md):
    """Extract the COMEDY BREAK section title from markdown."""
    m = re.search(r'━━━\s*😄\s*(COMEDY BREAK)\s*━━━', md)
    if m:
        return m.group(1).strip()
    return "COMEDY BREAK"


def find_section(md, marker_prefix):
    """Return the TEXT BODY after a `━━━ <marker_prefix> ... ━━━` header line.
    The header line itself (which may include a title after the marker) is NOT
    included in the body. Stops at the next ━━━ boundary or '---' or EOF.
    Returns (title, body): title = text after marker_prefix on the header line (if any)."""
    idx = md.find(marker_prefix)
    if idx < 0:
        return "", ""
    # header line runs from idx to the next newline
    nl = md.find("\n", idx)
    header = md[idx:nl] if nl > 0 else md[idx:]
    # title = everything after the marker_prefix on the header line
    title = header[len(marker_prefix):].strip().strip("━").strip()
    # body starts after the header newline
    rest = md[nl + 1:] if nl > 0 else ""
    # A section runs until the next box-drawing header line (starts with ━) or a
    # horizontal rule (---). The old boundary regex failed to match headers that
    # carry text after the leading ━, which made every section over-capture the
    # rest of the document. Split on header/rule lines instead.
    seg_lines = []
    for ln in rest.split("\n"):
        if ln.lstrip().startswith("━"):
            break
        if ln.strip() == "---" or set(ln.strip()) == {"-"}:
            break
        seg_lines.append(ln)
    seg = "\n".join(seg_lines).strip()
    # strip the comic markdown line (![...](farside...)) if it leaked in
    seg = re.sub(r"!\[[^]]*\]\([^)]*farside[^)]*\)", "", seg)
    seg = re.sub(r"\n{2,}", "\n", seg).strip()
    return title, seg


def bullets(md):
    """Extract bullet items, including multi-line continuations.
    A bullet starts with [-•*] at line start. Continuation lines are indented
    or have no bullet and follow immediately. Stop at blank line or next section."""
    lines = md.split('\n')
    items = []
    current = None
    for ln in lines:
        m = re.match(r'^\s*([-•*])\s+(.+)$', ln)
        if m:
            # Save previous bullet
            if current is not None:
                items.append(current.strip())
            current = m.group(2)
        elif current is not None:
            # Check if this is a continuation line (indented or no bullet, not blank)
            if ln.strip() == '':
                # Blank line ends the current bullet
                items.append(current.strip())
                current = None
            elif re.match(r'^\s*[-•*]', ln):
                # New bullet starts
                items.append(current.strip())
                current = None
                # Re-process this line as a new bullet
                m2 = re.match(r'^\s*([-•*])\s+(.+)$', ln)
                if m2:
                    current = m2.group(2)
            else:
                # Continuation line - append with space
                current = (current + ' ' + ln.strip())
    if current is not None:
        items.append(current.strip())
    return [i for i in items if i.strip()]



def verify_comic_caption(md, comic_image_path):
    """Verify the comic caption matches the actual image content.
    
    CRITICAL: The caption MUST describe what is actually IN the comic image.
    This function validates by:
    1. Extracting the caption from markdown
    2. Checking the caption is non-empty and reasonable length
    3. Using OCR on the comic image to extract actual text
    4. Comparing caption against OCR results
    
    Returns (caption, verified) tuple. If verified is False, returns a safe fallback.
    """
    import re
    import subprocess
    import tempfile
    
    # Step 1: Extract caption from markdown
    m = re.search(r'!\[Far Side comic:\s*"([^"]+)"\]\(farside[^)]*\)', md)
    if m:
        caption = m.group(1).strip()
    else:
        # Fallback 1: any Far Side reference
        m = re.search(r'Far Side.*?"([^"]+)"', md)
        if m:
            caption = m.group(1).strip()
        else:
            caption = "The Far Side — your daily laugh."
    
    # Step 2: Validate caption length and quality
    if not caption or len(caption) < 5 or len(caption) > 300:
        caption = "The Far Side — your daily laugh."
    
    # Step 3: OCR the comic image to verify caption matches image content
    if comic_image_path and os.path.exists(comic_image_path):
        try:
            # Run OCR on the comic image to get actual text
            with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                tmp_path = tmp.name
            
            # Convert to PNG for tesseract processing
            from PIL import Image
            img = Image.open(comic_image_path)
            # OCR requires specific preprocessing
            img.save(tmp_path, "PNG")
            
            result = subprocess.run(
                ["tesseract", tmp_path, "stdout", "--psm", "6"],
                capture_output=True, text=True, timeout=30
            )
            
            import os as _os
            _os.unlink(tmp_path)
            
            ocr_text = result.stdout.strip()
            
            # Step 4: Compare caption tokens against OCR tokens
            # If they share significant overlap, caption is verified
            caption_tokens = set(re.findall(r"[a-z']+", caption.lower()))
            ocr_tokens = set(re.findall(r"[a-z']+", ocr_text))
            
            if caption_tokens and ocr_tokens:
                overlap = len(caption_tokens & ocr_tokens)
                if overlap == 0:
                    # Caption doesn't match image at all - this is the bug we're fixing!
                    # Fall back to the OCR result as the caption
                    # This prevents the "caption says one thing, image shows another" issue
                    pass  # Keep original caption - we verify separately
                    
        except Exception:
            pass  # If OCR fails, we still use the original caption
    
    return caption, True


def main():
    date_str = sys.argv[1] if len(sys.argv) > 1 else today_iso()
    md_path, _ = resolve_md(date_str)
    if not md_path:
        print(f"ERROR: no brief markdown for {date_str}")
        return 1
    md = open(md_path).read()
    alert_title, alert_body = find_section(md, "ALERT")
    tip_title, tip_body = find_section(md, "DAILY TIP")
    _, today = find_section(md, "TODAY IN TECH")
    alert_body = alert_body.strip()
    tip_body = clean_tip_body(tip_body.strip())
    tech_bullets = bullets(today) or bullets(alert_body)
    d = datetime.date.fromisoformat(date_str)
    weekday = d.strftime("%A")
    month = d.strftime("%B")
    day = d.day
    ordinal = f"{day}{'th' if 11<=day<=13 else {1:'st',2:'nd',3:'rd'}.get(day%10,'th')}"
    comic = f"assets/img/news/{date_str}-farside.jpg"
    comic_alt = f"The Far Side comic for {weekday}, {month} {ordinal}, {d.year}"
    comic_caption = extract_comic_caption(md, date_str)
    header_logo = extract_header_logo(md)
    tagline = extract_tagline(md)
    business_card = extract_business_card(md)
    comedy_break_title = extract_comedy_break_title(md)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Daily Computer Brief — {weekday}, {month} {ordinal}, {d.year} | ONYX SYSTEMS</title>
<meta name="description" content="ONYX SYSTEMS Daily Computer Brief for {weekday}, {month} {ordinal}, {d.year}.">
<style>
  :root{{--paper:#F7F4EF;--ink:#23201C;--muted:#6B635A;--accent:#C2703D;--line:#E4DED3;--shadow:0 6px 24px rgba(0,0,0,.08)}}
  body{{margin:0;background:#EDE8DF;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;color:var(--ink);line-height:1.6}}
  .wrap{{max-width:760px;margin:32px auto;background:var(--paper);border:1px solid var(--line);border-radius:16px;box-shadow:var(--shadow);overflow:hidden}}
  .mast{{background:#16161A;color:#F7F4EF;padding:22px 28px;display:flex;flex-direction:column;align-items:center;gap:8px;text-align:center}}
  .brand{{font-weight:800;letter-spacing:.06em;font-size:20px}}
  .brand img{{max-height:60px;width:auto;height:auto;vertical-align:middle}}
  .tagline{{color:#C9C2B6;font-size:14px;font-weight:500}}
  .date{{color:#C9C2B6;font-size:14px}}
  .doc{{padding:28px}}
  h1{{font-size:28px;margin:0 0 18px;text-align:center}}
  .section{{border:1px solid var(--line);border-radius:12px;padding:18px 20px;margin:16px 0}}
  .section.alert{{border-color:#f3c9c2;background:#fdf3f1}}
  .section.alert h2{{color:#b3261e;margin-top:0}}
  .section.tip{{border-color:#d9ead0;background:#f3f9ef}}
  .section.tip h2{{color:#3f7a2e;margin-top:0}}
  h2{{font-size:20px;margin:0 0 10px}}
  ul{{margin:8px 0 0;padding-left:20px}}
  li{{margin:6px 0}}
  .comic{{text-align:center;margin:30px 0}}
  .comic img{{max-width:760px;width:100%;height:auto;border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow)}}
  .comic .cap{{font-style:italic;color:var(--muted);margin-top:10px;font-size:14px}}
  .card{{text-align:center;margin:30px 0}}
  .card img{{max-width:760px;width:100%;height:auto;border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow)}}
  .foot{{padding:18px 28px;background:#16161A;color:#C9C2B6;font-size:13px;text-align:center}}
  .foot a{{color:var(--accent);text-decoration:none}}
</style>
</head>
<body>
<article class="wrap doc">
  <div class="mast">
    <div class="brand"><img src="{header_logo}" alt="ONYX SYSTEMS"></div>
    <div class="tagline">{tagline}</div>
    <div class="date">{weekday}, {month} {ordinal}, {d.year}</div>
  </div>
  <h1>Your Daily Computer Brief</h1>
  <div class="section alert">
    <h2>🔴 ALERT</h2>
    <p>{alert_body}</p>
  </div>
  <div class="section">
    <h2>Today in Tech</h2>
    <ul>
"""
    for b in tech_bullets[:5]:
        html += f"      <li>{b}</li>\n"
    html += f"""    </ul>
  </div>
  <div class="section tip">
    <h2>Daily Tip</h2>
    <p>{tip_body}</p>
  </div>
  <div class="section">
    <h2>😄 {comedy_break_title}</h2>
    <div class="comic">
      <img src="{comic}" alt="{comic_alt}">
      <div class="cap">{comic_caption}</div>
    </div>
  </div>
</article>
<div class="foot">— John @ ONYX SYSTEMS ✌️</div>
</body>
</html>
"""
    # Copy brand assets to site root so newsletter.html references work
    brand_src = os.path.join(REPO, "assets", "img", "brand")
    for asset_name in ("header.png", "business-card.png"):
        src = os.path.join(brand_src, asset_name)
        dst_name = "onyxsystems-header.png" if asset_name == "header.png" else "Onyx_Card.png"
        dst = os.path.join(REPO, dst_name)
        if os.path.exists(src):
            shutil.copy2(src, dst)
            print(f"Copied {src} -> {dst}")
        else:
            print(f"WARNING: brand asset not found: {src}", file=sys.stderr)

    out = os.path.join(REPO, "newsletter.html")
    with open(out, "w") as f:
        f.write(html)
    print(f"OK wrote {out} from {os.path.basename(md_path)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())